### ISSUE TITLE
Investigate if we can use this same repo for logging-lite

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/chart-fluent-bit#10]
_From @leahnp on August 1, 2017 23:9_

We will use a very similar fluentbit deployment for our 'logging-lite' solution. 
Investigate if we can simply add an elasticsearch output plugin to this config and use it for logging-lite or if we need to create a separate repo. 

Depending on outcome, make issues to implement the work for a logging-lite fluentbit daemonset with an elasticsearch output plugin.

_Copied from original issue: samsung-cnct/kraken-logging-fluent-bit-daemonset#12_

**Comment by davidewatson** [comment]
We are using this for logging lite, so this should probably be closed.

**Comment by guineveresaenger** [comment]
I agree.
