### ISSUE TITLE
Bootstrap directions are out of date, dependency chain unclear

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/chart-fluent-bit#11]
The README refers to fluent-bit.yaml, which no longer exists in this repo.

It would also be great to explain how this chart is a sub-chart of our logging-chart, and provide a link.

**Comment by DStorck** [comment]
also going to update docs in container-fluent-bit

**Comment by DStorck** [comment]
initial work https://github.com/samsung-cnct/chart-fluent-bit/pull/12

**Comment by guineveresaenger** [comment]
Thank you so much, it is easier to find your way around now. :)
