### ISSUE TITLE
finish port of chart-fluent-bit to gitlab

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-fluent-bit#17]
- [x]  Follow [instructions](https://github.com/samsung-cnct/solas/blob/master/docs/gitlab.md) to edit`.gitlab-ci.yml` from [template](https://github.com/samsung-cnct/solas-chart/blob/master/.gitlab-ci.yml) The gitlab file is there but we have changed some of the structure since this was a test for the port to gitlab.  Please grab the newest version of `.gitlab-ci.yml` from the template and replace the existing file. 
- [x] also replace and edit  `build/build.sh` and `build/test.sh` according to instructions
- [x] make build.sh and test.sh executable
- [x] create secret variable in gitlab
- [x] add pipeline status badge to README
- [x] Remove the `Jenkinsfile` in the current repo.
- [x] When PR has merged, make sure that new image is being created on quay. Afterwards,  please head back to the [umbrella ticket](https://github.com/samsung-cnct/issues/issues/89) and check off the `chart-fluent-bit`

**Comment by DStorck** [comment]
work is done here: https://github.com/samsung-cnct/chart-fluent-bit/pull/18

**Comment by leahnp** [comment]
LGTM
