### ISSUE TITLE
Replace "latest" tag with version

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/chart-fluent-bit#8]
Replace "latest" tag with version for our fluent-bit image once our CI can push versioned releases.

**Comment by guineveresaenger** [comment]
Is this still blocked?

**Comment by coffeepac** [comment]
waiting for gitlab CI

**Comment by guineveresaenger** [comment]
Fixed as part of https://github.com/samsung-cnct/chart-fluent-bit/pull/13 which was part of https://github.com/samsung-cnct/solas-chart/issues/8.

**Comment by coffeepac** [comment]
work done elsewhere.  this is a no-op.

**Comment by guineveresaenger** [comment]
Bah. The particular PR for this is:

#13 

and it has not been merged. 
Reopening this.

ToReview: make sure #13 works as advertised.

**Comment by guineveresaenger** [comment]
Addressed by #13. Finally closing this.
